/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./src/components/Home.vue')['default']
    NewFileDialog: typeof import('./src/components/dialog/NewFileDialog.vue')['default']
    NewFolderDialog: typeof import('./src/components/dialog/NewFolderDialog.vue')['default']
    OpenFileDialog: typeof import('./src/components/dialog/OpenFileDialog.vue')['default']
    Root: typeof import('./src/components/Root.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starred: typeof import('./src/components/pages/Starred.vue')['default']
    StatisticsNavDrawer: typeof import('./src/components/drawer/StatisticsNavDrawer.vue')['default']
  }
}
