/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/dialog/NewFileDialog copy.vue')['default']
    Dialog: typeof import('./src/components/dialog/Dialog.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    NewFileDialog: typeof import('./src/components/dialog/NewFileDialog.vue')['default']
    NewFolderDialog: typeof import('./src/components/dialog/NewFolderDialog.vue')['default']
    OpenFileDialog: typeof import('./src/components/dialog/OpenFileDialog.vue')['default']
  }
}
